import json
from fpdf import FPDF


def clean(text):
    """Remove ALL non-ASCII characters including emojis to prevent fpdf crashes"""
    if not text:
        return ""
    result = ''
    for c in str(text):
        if ord(c) < 128:
            result += c
        else:
            result += ' '
    while '  ' in result:
        result = result.replace('  ', ' ')
    return result.strip()


def build_markdown(course_data):
    d = course_data
    lines = [f"# {d['topic']} - Course Curriculum", ""]
    lines.append(f"**Audience:** {d['audience']}")
    lines.append(f"**Duration:** {d['duration']} weeks")
    lines.append(f"**Generated:** {d['generated_at']}")
    lines.append("\n---\n")
    lines.append("## Curriculum Timeline\n")
    for w in d.get("weeks", []):
        lines.append(f"### Week {w.get('week_number')} - {w.get('title')}")
        lines.append(f"- **Objectives:** {w.get('objectives')}")
        lines.append(f"- **Topics:** {w.get('topics')}")
        lines.append(f"- **Exercise:** {w.get('exercise')}\n")

    assessments = d.get("assessments", {})
    if assessments and not assessments.get("error"):
        lines.append("## Assessments\n")
        opt_labels = ["A", "B", "C", "D"]
        for q in assessments.get("quizzes", []):
            lines.append(f"**Week {q.get('week_number')} Quiz:** {q.get('question')}")
            for i, opt in enumerate(q.get("options", [])):
                label = opt_labels[i] if i < 4 else str(i+1)
                opt_text = opt
                for pfx in ["A) ","B) ","C) ","D) ","A. ","B. ","C. ","D. "]:
                    if opt.startswith(pfx):
                        opt_text = opt[len(pfx):]
                        break
                lines.append(f"  - {label}) {opt_text}")
            lines.append(f"  *Answer:* {q.get('correct_answer')}\n")

        lines.append("### Assignments\n")
        for a in assessments.get("assignments", []):
            lines.append(
                f"- **Week {a.get('week_number')} - {a.get('title')}:** {a.get('description')}"
            )

        lines.append("\n### Grading Rubric\n")
        for r in assessments.get("grading_rubric", []):
            lines.append(
                f"- **{r.get('criteria')}** ({r.get('weight_percent')}%): {r.get('description')}"
            )

    lines.append("\n---")
    lines.append("Generated by CourseCraft AI - Developed by Agha Wafa Abbas")
    return "\n".join(lines)


def build_pdf(course_data):
    d = course_data
    pdf = FPDF()
    pdf.set_margins(20, 20, 20)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    pw = pdf.w - 40  # usable page width

    def write_line(text, size=10, bold=False, ln_after=4):
        try:
            style = "B" if bold else ""
            pdf.set_font("Helvetica", style, size)
            pdf.multi_cell(pw, 7, clean(text))
            pdf.ln(ln_after)
        except Exception:
            pass

    # ---- TITLE ----
    write_line(
        f"{d['topic']} - Course Curriculum",
        size=18, bold=True, ln_after=2
    )
    write_line(
        f"Audience: {d['audience']}  |  Duration: {d['duration']} weeks  |  {d['generated_at']}",
        size=10, ln_after=6
    )

    # ---- TIMELINE ----
    write_line("Curriculum Timeline", size=14, bold=True, ln_after=3)
    for w in d.get("weeks", []):
        write_line(
            f"Week {w.get('week_number', '')} - {w.get('title', '')}",
            size=11, bold=True, ln_after=1
        )
        write_line(f"Objectives: {w.get('objectives', '')}", size=10, ln_after=1)
        write_line(f"Topics: {w.get('topics', '')}", size=10, ln_after=1)
        write_line(f"Exercise: {w.get('exercise', '')}", size=10, ln_after=4)

    # ---- ASSESSMENTS ----
    assessments = d.get("assessments", {})
    if assessments and not assessments.get("error"):
        pdf.add_page()
        write_line("Assessments", size=14, bold=True, ln_after=3)

        quizzes = assessments.get("quizzes", [])
        if quizzes:
            write_line("Weekly Quizzes", size=11, bold=True, ln_after=2)
            opt_labels = ["A", "B", "C", "D"]
            for q in quizzes:
                write_line(
                    f"Week {q.get('week_number')}: {q.get('question', '')}",
                    size=10, bold=True, ln_after=1
                )
                for i, opt in enumerate(q.get("options", [])):
                    label = opt_labels[i] if i < 4 else str(i + 1)
                    opt_text = opt
                    for pfx in ["A) ", "B) ", "C) ", "D) ", "A. ", "B. ", "C. ", "D. "]:
                        if opt.startswith(pfx):
                            opt_text = opt[len(pfx):]
                            break
                    write_line(f"  {label}) {opt_text}", size=10, ln_after=1)
                write_line(
                    f"Answer: {q.get('correct_answer', '')}",
                    size=10, ln_after=3
                )

        assignments = assessments.get("assignments", [])
        if assignments:
            write_line("Assignments", size=11, bold=True, ln_after=2)
            for a in assignments:
                write_line(
                    f"Week {a.get('week_number')} - {a.get('title', '')}: {a.get('description', '')}",
                    size=10, ln_after=2
                )

        rubric = assessments.get("grading_rubric", [])
        if rubric:
            write_line("Grading Rubric", size=11, bold=True, ln_after=2)
            for r in rubric:
                write_line(
                    f"{r.get('criteria', '')} ({r.get('weight_percent', '')}%): {r.get('description', '')}",
                    size=10, ln_after=2
                )

    # ---- KNOWLEDGE GRAPH ----
    kg = d.get("knowledge_graph", {})
    nodes = kg.get("nodes", [])
    edges = kg.get("edges", [])
    if nodes:
        pdf.add_page()
        write_line("Knowledge Graph - Core Concepts", size=14, bold=True, ln_after=3)
        write_line("Concepts:", size=11, bold=True, ln_after=1)
        for n in nodes:
            write_line(f"  - {n.get('label', n.get('id', ''))}", size=10, ln_after=1)
        pdf.ln(3)
        write_line("Concept Relationships:", size=11, bold=True, ln_after=1)
        id_to_label = {n.get("id"): n.get("label", n.get("id", "")) for n in nodes}
        for e in edges:
            src = id_to_label.get(e.get("source"), e.get("source", ""))
            tgt = id_to_label.get(e.get("target"), e.get("target", ""))
            write_line(f"  {src}  ->  {tgt}", size=10, ln_after=1)

    # ---- FOOTER ----
    pdf.ln(8)
    write_line(
        "Generated by CourseCraft AI - Developed by Agha Wafa Abbas | Powered by Groq + Llama-3",
        size=9, ln_after=0
    )

    return bytes(pdf.output())


def build_scorm_json(course_data):
    return json.dumps(course_data, indent=2, ensure_ascii=False)


def build_linkedin_snippet(course_data):
    d = course_data
    assess = d.get("assessments", {})
    quiz_count = len(assess.get("quizzes", [])) if assess and not assess.get("error") else 0
    kg = d.get("knowledge_graph", {})
    node_count = len(kg.get("nodes", [])) if kg else 0

    return (
        f"Just generated a full {d['duration']}-week course on \"{d['topic']}\" "
        f"using CourseCraft AI - my custom Agentic AI system powered by Groq + Llama-3!\n\n"
        f"Course highlights:\n"
        f"- {d['duration']} weeks of AI-structured curriculum\n"
        f"- {quiz_count} AI-generated quizzes with grading rubric\n"
        f"- {node_count} core concepts mapped in knowledge graph\n"
        f"- Multi-agent architecture (Curriculum Designer + Assessment Critic)\n"
        f"- Exported as PDF, Markdown & JSON in one click\n\n"
        f"Target audience: {d['audience']} learners\n\n"
        f"#AgenticAI #GroqAPI #Llama3 #EdTech #AIEngineering #CourseCraftAI"
    )